place KEYSTORE and PASS out of the container

diff --git a/tools/generate_keystore b/tools/generate_keystore
--- a/tools/generate_keystore
+++ b/tools/generate_keystore
@@ -1,20 +1,30 @@
 #!/bin/bash
-set -x
-KEYSTOREDIR=~/keystore
-mkdir -p $KEYSTOREDIR
-cd $KEYSTOREDIR || exit 1
+set -xe
+if [ -z "$KEYSTORE" ]; then
+	echo "KEYSTORE variable missing, set it to the place of keystore file to be generated"
+	exit 1
+fi
+if [ -z "$KEYSTOREPASS" ]; then
+	echo "KEYSTOREPASS variable missing, set it to the passphrase of the generated keystore"
+	exit 1
+fi
 
-KEYSTOREFILE=keystore.pk12
-
+KEYSTOREDIR=$(dirname "$KEYSTORE")
+KEYSTOREFILE=$(basename "$KEYSTORE")
 if [ ! -f "$KEYSTOREFILE" ]
 then
+  TMP=$(mktemp -d)
+  cd $TMP
   SUBJ="/C=HU/ST=Pest/L=Hungary/O=Kozossegi Digitalis Eszkozok Alapitvany/OU=Org/CN=*.demokracia.rulez.org"
-  KEYSTOREPASS="changit"
   ALIAS="PDEngineKeys"
   PRIVKEYFILE=selfsigned.key
   CERTFILE=selfsigned.crt
   openssl req -x509 -newkey rsa:2048 -keyout $PRIVKEYFILE -out $CERTFILE -days 365 -nodes -subj "$SUBJ"
-  openssl pkcs12 -name "$ALIAS" -export -in $CERTFILE -inkey $PRIVKEYFILE -out $KEYSTOREFILE -passout pass:"$KEYSTOREPASS"
-  rm $PRIVKEYFILE $CERTFILE
-  chmod og-r-w-x $KEYSTOREFILE 
+  openssl pkcs12 -name "$ALIAS" -export -in $CERTFILE -inkey $PRIVKEYFILE -out "$KEYSTOREFILE" -passout pass:"$KEYSTOREPASS"
+  sudo mkdir -p "$KEYSTOREDIR"
+  sudo cp $KEYSTOREFILE "$KEYSTOREDIR/"
+  sudo chmod og-w "$KEYSTOREDIR"
+  sudo chown $USERNAME "$KEYSTORE"
+  sudo chmod og-r-w-x "$KEYSTORE"
+  rm -r $TMP
 fi
